// Generated by https://quicktype.io

export interface Resident {
    id:       number;
    name:     string;
    lastname: string;
    email:    string;
    phone:    number;
    address:  string;
    password: string;
}
